src/motorcycle_sales.Web/Controllers/AdvertisementController.cs
using System.Globalization;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using motorcycle_sales.Core;
using motorcycle_sales.Core.Entities;
using motorcycle_sales.Core.Entities.AdvertisementAggregate;
using motorcycle_sales.Core.Interfaces;
using motorcycle_sales.Core.ProjectAggregate.Events;
using motorcycle_sales.Core.Services;
using motorcycle_sales.Core.Specifications;
using motorcycle_sales.SharedKernel.Interfaces;
using motorcycle_sales.Web.ViewModels;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace motorcycle_sales.Web.Controllers;

[Authorize]
public class AdvertisementController : Controller
{
    private readonly IAdvertisementService _advertisementService;
    private readonly IReadRepository<Brand> _brandRepository;
    private readonly IReadRepository<Model> _modelRepository;
    private readonly IRepository<Advertisement> _advertisementRepository;
    private readonly IRepository<UserSearchFilter> _userSearchFilteRepository;
    private readonly IRepository<AdvertisementSearchFilter> _advertisementFilterRepository;
    private readonly IHostingEnvironment _hostingEnvironment;
    private readonly ILogger<AdvertisementController> _logger;
    private readonly UserManager<ApplicationUser> _userManager;

    public AdvertisementController(IAdvertisementService advertisementService
        , IReadRepository<Model> modelRepository
        , IReadRepository<Brand> brandRepository
        , IRepository<Advertisement> advertisementRepository
        , IRepository<UserSearchFilter> userSearchFilterRepository
        , IHostingEnvironment hostingEnvironment
        , ILogger<AdvertisementController> logger
        , IUserSearchFilterService userSearchFilterService
        , UserManager<ApplicationUser> userManager
        , IRepository<AdvertisementSearchFilter> advertisementFilterRepositroy)
    {
        _advertisementService = advertisementService;
        _brandRepository = brandRepository;
        _modelRepository = modelRepository;
        _advertisementRepository = advertisementRepository;
        _userSearchFilteRepository = userSearchFilterRepository;
        _hostingEnvironment = hostingEnvironment;
        _logger = logger;
        _userManager = userManager;
        _advertisementFilterRepository = advertisementFilterRepositroy;
    }

    public async Task<IActionResult> Create()
    {
        CreateAdvertisementViewModel createAdvertisementModel = new CreateAdvertisementViewModel();
        List<Brand> brands = await _brandRepository.ListAsync();
        createAdvertisementModel.Brands = new SelectList(brands, "Id", "Name");
        
        createAdvertisementModel.Years = new SelectList(Enumerable.Range(1950, (DateTime.Now.Year - 1950) + 1), 2000);

        var months = CultureInfo
            .GetCultureInfo("en-GB")
            .DateTimeFormat
            .MonthNames.Select((monthName, Index) => new SelectListItem
            {
                Value = (Index + 1).ToString(),
                Text = monthName
            });

        createAdvertisementModel.Months = new SelectList(months, "Value", "Text", 1);


        return View(createAdvertisementModel);
    }

    //[Authorize(Policy = "Permission.Advertisement.Edit")]
    [HttpPost]
    public async Task<ActionResult> CreateAsync(CreateAdvertisementViewModel createAdvertisementModel)
    {
        _logger.LogDebug("Testting log controller asdf");

        if (!ModelState.IsValid)
        {
            createAdvertisementModel.Brands = new SelectList(Enumerable.Empty<SelectList>()) ;

            return View(createAdvertisementModel);
        }         


        string uniqueFileName = null;

        if (createAdvertisementModel.Photo != null)
        {
            string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images");
            uniqueFileName = Guid.NewGuid().ToString() + createAdvertisementModel.Photo.FileName; ;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);
            createAdvertisementModel.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
        }

        // TODO replace with mapper
        Advertisement advertisement = new Advertisement()
        {
            ModelId = createAdvertisementModel.ModelId,
            BrandId = createAdvertisementModel.BrandId,
            Modification = createAdvertisementModel.Modification,
            EngineType = createAdvertisementModel.EngineType,
            HorsePower = createAdvertisementModel.HorsePower,
            EngineCapacity = createAdvertisementModel.EngineCapacity,
            TransmissionType = createAdvertisementModel.TransmissionType,
            CoolingSystemType = createAdvertisementModel.CoolingSystemType,
            Category = createAdvertisementModel.Category,
            ProductionYear = createAdvertisementModel.ProductionYear,
            ProductionMonth = createAdvertisementModel.Month,
            Price = createAdvertisementModel.Price,
            Mileage = createAdvertisementModel.Mileage,
            Description = createAdvertisementModel.Description,
            PhotoPath = uniqueFileName,
            UserId = User.FindFirstValue(ClaimTypes.NameIdentifier),
            CreationDate = DateTime.Now,
            Status = AdvertisementStatus.Pending
        };

        _logger.LogDebug("Inserting new advertisement");

        UserSearchFilterSpecification x = new UserSearchFilterSpecification(advertisement);

        // Add event for email notification
        //advertisement.Events.Add(new NewAdvertisementCreatedEvent(advertisement));

        await _advertisementRepository.AddAsync(advertisement);


        return RedirectToAction("index", "home");
    }

    [AllowAnonymous]
    public async Task<JsonResult> GetModels(int id)
    {
        // TODO Use specifications 
        List<Model> models = await _modelRepository.ListAsync(); 
        List<Model> modelsFiltered = models.Where(model => (model.BrandId == id)).ToList();
        //modelsFiltered.Insert(0, new Model
        //{
        //    Name = ""
        //});
        return Json(new SelectList(modelsFiltered, "Id", "Name"));
    }

    [HttpGet]
    [AllowAnonymous]
    public async Task<ActionResult> View(int id)
    {
        var advertisementByIdSpec = new AdvertisementWithDetailsSpecification(id);
        var advertisement = await _advertisementRepository.GetBySpecAsync(advertisementByIdSpec);

        if (advertisement == null)
            return NotFound();

        return View(advertisement);
    }

    [HttpGet]
    [AllowAnonymous]
    public async Task<ActionResult> Search()
    {
        SearchAdvertisementViewModel model = new SearchAdvertisementViewModel();

        List<Brand> brands = await _brandRepository.ListAsync();
        //brands.Insert(0, new Brand
        //{
        //    Name = ""
        //});
        model.Brands = new SelectList(brands, "Id", "Name");

        return View(model);
    }

    [HttpPost]
    [AllowAnonymous]
    public async Task<ActionResult> Search(SearchAdvertisementViewModel model)
    { 
        model.Advertisements = await _advertisementService.GetAdvertisementsByFilter(model.AdvertisementSearchFilter);

        List<Brand> brands = await _brandRepository.ListAsync();
        brands.Insert(0, new Brand
        {
            Name = ""
        });

        model.Brands = new SelectList(brands, "Id", "Name", String.Empty);

        return View(model);
    }

    public async Task<IActionResult> SaveSearchFilter(AdvertisementSearchFilter searchFilter)
    {
        var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

        var userSearchFilter = new UserSearchFilter()
        {
            AdvertisementSearchFilter = searchFilter,
            FilterName = "Filter ",
            UserId = currentUserId,
            CreateTime = DateTime.Now
        };

        _userSearchFilteRepository.AddAsync(userSearchFilter);

        return Ok();
    }

    public async Task<IActionResult> AddAdvertisementToFavorite(int advertisementId, bool add)
    {
        var advertisement = await _advertisementRepository.GetByIdAsync(advertisementId);
        var user = await _userManager.GetUserAsync(HttpContext.User);

        if (add)
        {
            if (user.FavoriteAdvertisements.FindIndex(ad => ad.Id == advertisementId) == -1)
                user.FavoriteAdvertisements.Add(advertisement);
        }
        else
        {
            int index = user.FavoriteAdvertisements.FindIndex(ad => ad.Id == advertisementId);
            if (index != -1)
                user.FavoriteAdvertisements.RemoveAt(index);
        }

        await _advertisementRepository.SaveChangesAsync();
        var result = await _userManager.UpdateAsync(user);
        if (!result.Succeeded)
            return BadRequest();

        return Ok();
    }

    [AllowAnonymous]
    public async Task<JsonResult> IsFavorite(int advertisementId)
    {
        var user = await _userManager.GetUserAsync(HttpContext.User);

        // If no user is logged in
        if (user == null)
            return Json(false);

        int index = user.FavoriteAdvertisements.FindIndex(ad => ad.Id == advertisementId);
        bool found = index != -1;

        return Json(found);
    }

    [HttpGet]
    public async Task<ActionResult> Favorites()
    {
        var user = await _userManager.GetUserAsync(HttpContext.User);
        if (user == null)
            return NotFound();

        // TODO for optimize
        List<Advertisement> advertisements = user.FavoriteAdvertisements;
        return View(advertisements);
    }
}

src/motorcycle_sales.Web/Views/Shared/_AdminMenu.cshtml
<div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark min-vh-100">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white sidebar">
        <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <span class="fs-5 d-none d-sm-inline">Admin Menu</span>
        </a>
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
            <li>
                <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-people"></i><span class="ms-1 d-none d-sm-inline">User Managament</span>
                </a>
                <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                    <li class="w-100">
                        <a asp-controller="administration" asp-action="listRoles" class="nav-link align-middle px-0">
                            <i class="fa-solid fa-angle-right"></i> <span class="ms-1 d-none d-sm-inline">Roles</span>
                        </a>
                    </li>
                    <li class="w-100">
                        <a asp-controller="administration" asp-action="listUsers" class="nav-link align-middle px-0">
                            <i class="fa-solid fa-angle-right"></i> <span class="ms-1 d-none d-sm-inline">Users</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                    <i class="fas fa-book fa-lg"></i> <span class="ms-1 d-none d-sm-inline">Catalog</span>
                </a>
                <ul class="collapse show nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                    <li class="w-100">
                        <a asp-controller="catalogManage" asp-action="listBrands" class="nav-link align-middle px-0">
                            <i class="fa-solid fa-angle-right"></i> <span class="ms-1 d-none d-sm-inline">Brands</span>
                        </a>
                    </li>
                    <li class="w-100">
                        <a asp-controller="catalogManage" asp-action="listModels" class="nav-link align-middle px-0">
                            <i class="fa-solid fa-angle-right"></i> <span class="ms-1 d-none d-sm-inline">Models</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                    <i class="far fa-list-alt" fa-lg></i> <span class="ms-1 d-none d-sm-inline">Advertisements</span>
                </a>
                <ul class="collapse show nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                    <li class="w-100">
                        <a asp-controller="advertisementManage" asp-action="listConfirm" class="nav-link align-middle px-0">
                            <i class="fa-solid fa-angle-right"></i> <span class="ms-1 d-none d-sm-inline">Confirm</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

src/motorcycle_sales.Web/Views/Shared/_AdvertisementsList.cshtml
@model IEnumerable<Advertisement>

<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var advertisement in Model)
    {

        var photoPath = "~/Images/" + (advertisement.PhotoPath ?? "nophoto.jpg");
        var price = advertisement.Price > 0 ? advertisement.Price + " EUR" : "По договаряне";
        <div class="col">
            <div class="card motorcard shadow hover-zoom">

                <div class="card-header" style="background-color: #e3f2fd;">
                    <h3>@advertisement.Brand.Name @advertisement.Model.Name</h3>
                    <p> @advertisement.CreationDate.ToString("dd/MM/yyyy HH:mm") | @advertisement.User.City</p>
                </div>


                <img class="card-img-top image-thumbnail" src="@photoPath" asp-append-version="true" />
                <div>
                    <h4 class="ad-price">@price</h4>
                </div>

                <a asp-controller="advertisement" asp-action="view"
               asp-route-id="@advertisement.Id"
               class="stretched-link"></a>
            </div>
@*              <div class="card-footer bg-transparent" style ="border: 1px solid black; border-top: 0;">Footer</div>*@
        </div>
        @*        <div class="card m-3 card-3" style="width: 18rem;">
            <img class="card-img-top" src="@photoPath" alt="Card image cap" asp-append-version="true">
            <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
            </div>*@
    }
</div>

src/motorcycle_sales.Web/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager;
@inject UserManager<ApplicationUser> userManager;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - motorcycle_sales.Web</title>

    <environment names="Development">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="row" style="max-width: 100%;">
        @{
            var isAdmin = false;
            var mainBodyClass = "";

            var user = await userManager.GetUserAsync(User);
            if (user != null)
            {
                var roles = await userManager.GetRolesAsync(user);
                if (roles.Any())
                    isAdmin = true;
            }
        }

        @if (isAdmin)
        {
            @Html.Partial("_AdminMenu")

            ;
            mainBodyClass = "col-auto col-md-9";
        }

        <div class="@mainBodyClass">

            <div class="container ">
                <div class="navbar shadow navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>

                            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                                <img src="~/images/logo3.png" width="80" height="80" class="d-inline-block align-top" alt="">
                            </a>
                        </div>
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav">
                                <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
                                <li><a asp-area="" asp-controller="Advertisement" asp-action="Create" class="nav-link">List an item</a></li>
                                <li><a asp-area="" asp-controller="Advertisement" asp-action="Search" class="nav-link">Search</a></li>
                                @if (signInManager.IsSignedIn(User))
                                {
                                    <li><a asp-area="" asp-controller="Advertisement" asp-action="Favorites" class="nav-link">Favorites ❤</a></li>
                                }
                            </ul>
                            <ul class="navbar-nav ms-auto">
                                @if (signInManager.IsSignedIn(User))
                                {
                                    var userID = User.FindFirstValue(ClaimTypes.NameIdentifier);

                                    <div class="dropdown">
                                        <a class="nav-link" href="" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                            Profile
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                            <li>
                                                <a class="dropdown-item" asp-controller="account" asp-action="profile" asp-route-userId="@userID">Profile</a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" asp-controller="advertisement" asp-action="favorites" asp-route-userId="@userID">Favorites</a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" asp-controller="account" asp-action="myadvertisements" asp-route-userId="@userID">My advertisements</a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" asp-controller="account" asp-action="filters" asp-route-userId="@userID">Filters</a>
                                            </li>
                                        </ul>
                                    </div>

                                    <li class="nav-item">
                                        <a asp-controller="account" asp-action="logout" class="nav-link">Logout @User.Identity.Name</a>
                                    </li>
                                }
                                else
                                {
                                    <li>
                                        <a asp-controller="account" asp-action="register" class="nav-link">Register</a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="account" asp-action="login" class="nav-link">Login</a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
            <br />

            <div class="modal fade" id="form-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel"></h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="form-modal-confirm" tabindex="-1" aria-labelledby="modal-confirm-label" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            <button type="button" class="btn btn-primary" id="form-modal-confirm-button">Confirm</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container body-content">
                @RenderBody()
            </div>

            <div class="container footer">

                <hr />
                <p>&copy; @DateTime.Today.Year - motorcycle_sales.Web</p>

            </div>
        </div>



    </div>


    <environment names="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @await RenderSectionAsync("scripts", required: false).ConfigureAwait(false)
</body>
</html>